### PR TITLE
Fix #77

### LINKED ISSUE #77: Unable to change Docker storage path from UI
The Docker storage path is not changed when changing it in UI. The new input value is stored, but the data keeps being stored in the default path (```/var/lib/docker```).

Apparently you must have to have an existing file in ```/etc/docker/daemon.json```… If you do, the function works just fine. But in my fresh "Raspberry Pi OS" installation the file did not exist (even the directory ```/etc/docker``` didn't exist), even after changing the Docker storage path value in the UI.

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/9a54f3cfca7377e667dbc5e55be0dcc6902da81a/usr/sbin/omv-installdocker#L320-L349

image

### PR DESCRIPTION
**Pull request by taai**
Make sure file ```/etc/docker/daemon.json``` file exists to be able to change the Docker storage path.

### CODE REVIEW

**Comment by ryecoaaron** [comment]
I don't know why the /etc/docker directory wouldn't exist but it should be the job of the docker-ce package to maintain it.  And the /etc/docker/daemon.json does not need to exist.  If it does not exist, the created file will be copied in.

**Comment by taai** [comment]
@ryecoaaron According to [documentation](https://docs.docker.com/config/daemon/#configure-the-docker-daemon), you have to create the ```/etc/docker/daemon.json``` file yourself. So, I still think that my fix is valid. 😉 

> To configure the Docker daemon using a JSON file, create a file at /etc/docker/daemon.json on Linux systems, or C:\ProgramData\docker\config\daemon.json on Windows.

By the way, the script (even before my changes) overrides existing file. What if there is additional configuration options in the ```/etc/docker/daemon.json``` file…?! 😏

**Comment by ryecoaaron** [comment]
> According to [documentation](https://docs.docker.com/config/daemon/#configure-the-docker-daemon), you have to create the /etc/docker/daemon.json file yourself. So, I still think that my fix is valid.

If you specify a path in the plugin, it will create a temp version of the config file in /tmp on line 327 - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/sbin/omv-installdocker#L327

Then, it compares the temp version with /etc/docker/daemon.json.  If it is different (it would be if it didn't exist), it will copy from /tmp to /etc/docker/ creating the file in line 335 https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/sbin/omv-installdocker#L335  What am I missing?

> By the way, the script (even before my changes) overrides existing file. What if there is additional configuration options in the /etc/docker/daemon.json file…?!

If you are going to maintain a custom daemon.json file, then you leave the path empty in the plugin.  It won't touch it then.

**Comment by taai** [comment]
> Then, it compares the temp version with /etc/docker/daemon.json. If it is different (it would be if it didn't exist), it will copy from /tmp to /etc/docker/ creating the file in line 335 https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/sbin/omv-installdocker#L335 What am I missing?

You are missing the fact that the directory ```/etc/docker``` does not exist and existing code fails to copy that file. My fix takes care of that.

**Comment by taai** [comment]
@ryecoaaron I would like you to know that this script is using global variables that can lead to unexpected results… 😉 

Here is a test case for you to understand:

```bash
foo1()
{
  # this variable will "leak", will be a global variable
  status=1
}

bar1()
{
  echo "status: ${status}"
}

foo2()
{
  # this variable will "stay" in the function
  local localStatus=1
}

bar2()
{
  echo "status: ${localStatus}"
}

foo1
bar1
foo2
bar2
```

**Comment by taai** [comment]
@ryecoaaron I spent some time to improve the function. I tested multiple cases (non existing file, existing file, empty file, file with the ```data-root``` key, file with multiple keys, file with multiple keys and without ```data-root``` key) – it works. I'm happy to contribute. 😃

**Comment by ryecoaaron** [comment]
> You are missing the fact that the directory /etc/docker does not exist and existing code fails to copy that file. My fix takes care of that.

Fine, we can create the directory.  I have never seen the directory not exist though.

> I would like you to know that this script is using global variables that can lead to unexpected results…

 I know they are global (been shell script for 20 years).  Some of them are used in more than one function.  I like the ones that might be changed to be at the top.  I do not want to move them.

Changing to using jq and cat'ing the file instead of copying are just doing the same thing the previous code was doing.  I do not want to only change data-root either.  The point is that omv-extras is create a config file that is known to work.  If a noob puts all kinds of bad settings in there, I want the plugin to reset the config file.  If you need other settings, just leave the path blank and you can do as you wish.

That said, I already have a couple of the omv-extras ported to saltstack (just waiting on saltstack 3005 to be in omv repos).  I will port this script to saltstack then as well.  If you want to contribute, I would much more interested in this script in saltstack than fixing things that I have no reports of being broken.

**Comment by taai** [comment]
@ryecoaaron My apologies for late answer.

> I know they are global (been shell scripting for 20 years). Some of them are used in more than one function. I like the ones that might be changed to be at the top. I do not want to move them.

To clear any misunderstandings… I didn't assume anything and didn't try to call anyone a noob or something like that. 😉 Some could also not know these things – I better say and question something instead of assuming that everything is meant to be like that (in which case there is a possibility that when there are many contributors something could go very wrong when everybody accepts things as they are and nobody is looking for possibility of issues)… I hope you understand what do I mean.

I usually avoid global variables, especially the ones that have very generic name (with no prefixes or namespaces) and could be used elsewhere and lead to unexpected results… But, if you say that the variables are "in control", I'm OK with that. 👍 

> Changing to using jq and cat'ing the file instead of copying are just doing the same thing the previous code was doing.

I chose ```jq``` because it is more correct tool to use to change options in JSON objects (the configuration file). Also I checked if OMV is using it and it is using it, so it must be already installed and I can use it it my fix. 😉 About using ```cat``` instead of ```cp``` – I assumed that in some cases ```cp``` changes permissions of the file that is being overridden. I could not find any proof for that, so, in this point I'm OK, if you want me to use ```cp``` instead of ```cat```. 🤷 Why I'm using ```cat``` at all is because ```jq``` is not meant to change a file "in place", otherwise I would not need ```cat``` or ```cp``` at all. 😅 

>  If a noob puts all kinds of bad settings in there, I want the plugin to reset the config file.

Think about contributors – there are [other options](https://docs.docker.com/config/daemon/) that could be in that file ( ```/etc/docker/daemon.json``` ) and which contributors could potentially want to test… Also, it is not very nice to override a config file without any warnings while it is possible to change exactly the one thing that is displayed in user interface. I'm offering to do things "less invasive"  – with ```jq```, changing only single option and not deleting other options that could possibly be there. 😉 

From UI/UX perspective – if you want to "reset" something, you should make a "reset" button. In this case overriding all possible options while user thinks he is changing only single option, is not good user experience. I get it that probability that someone is adding additional settings in that configuration file is low, but it is not zero, so, why not to prevent something preventable (frustration, issue report)?! 😉 

> If you want to contribute, I would much more interested in this script in saltstack than fixing things that I have no reports of being broken.

Well, I did report an [issue](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues/77), so, you **do have** a report of a thing that is broken. 😉 And I also contributed instead of just reporting issues.

**Comment by ryecoaaron** [comment]
> I chose jq because it is more correct tool to use to change options in JSON objects (the configuration file).

This is correct and I use jq all the time.  But the plugin isn't changing options.  It is completely re-writing the file as OMV does in almost all cases.

> Think about contributors – there are [other options](https://docs.docker.com/config/daemon/) that could be in that file ( /etc/docker/daemon.json ) and which contributors could potentially want to test…

I have no desire to maintain a full docker-like plugin in the omv-extras plugin.  Leaving the path blank allows you to use whatever options you want without omv-extras interfering.

> Also, it is not very nice to override a config file without any warnings while it is possible to change exactly the one thing that is displayed in user interface

Sorry.  That is how OMV works.  If you change the samba config file, it is overwritten.  It doesn't explicitly say this.  Not sure how this is any different.

> From UI/UX perspective – if you want to "reset" something, you should make a "reset" button. In this case overriding all possible options while user thinks he is changing only single option,

If we follow that logic, every plugin would need a "reset" button instead of a save button.

> Well, I did report an https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues/77, so, you do have a report of a thing that is broken. wink And I also contributed instead of just reporting issues.

I honestly never saw that report.  I responded to that.  I am not finding a bug either.

I'm sorry I don't want to make omv-extras like you want.  All I can recommend is write a plugin of your own if you want these advanced features.  I am closing this request because I am going to convert the script to saltstack.

**Pull request closed without merging**
